spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/SpringCloud_shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 8801
env:
  dev4